name: drona-x
services:
  app1:
    image: driver-image
    container_name: driver
    build:
      context: ../../driver
      dockerfile: ../../driver/Dockerfile
    ports:
      - "8083:8086"

  app2:
    image: order-service-image
    container_name: order-service
    build:
      context: ../../order-service
      dockerfile: ../../order-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://drona-mysql:3306/mydb
      SPRING_REDIS_HOST: drona-redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: drona-kafka:9092
    ports:
      - "8082:8084"

  app3:
    image: matching-engine-image
    container_name: matching-engine
    build:
      context: ../../matching-engine
      dockerfile: ../../matching-engine/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://drona-mysql:3306/mydb
      SPRING_REDIS_HOST: drona-redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: drona-kafka:9092
    ports:
      - "8081:8085"